# Generated by Django 3.0.5 on 2020-05-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_auto_20200504_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='background',
            field=models.CharField(default='background', max_length=30),
            preserve_default=False,
        ),
    ]
