# Generated by Django 3.0.5 on 2020-06-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_genre_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='background',
        ),
    ]
