# Generated by Django 3.0.5 on 2020-10-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0005_remove_genre_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('h1', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Texto maior')),
                ('span', models.CharField(max_length=100, verbose_name='Texto menor')),
            ],
        ),
    ]
