# Generated by Django 3.0.5 on 2020-10-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0007_auto_20201004_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='buylink',
            field=models.CharField(default=0, max_length=200, verbose_name='Link para compra'),
            preserve_default=False,
        ),
    ]
