# Generated by Django 3.0.5 on 2020-10-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0008_music_buylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='h1',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Texto maior'),
        ),
    ]
