# Generated by Django 3.0.5 on 2020-10-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0009_auto_20201004_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='buylink',
        ),
        migrations.AddField(
            model_name='music',
            name='spotify',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
