# Generated by Django 3.0.5 on 2020-10-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0010_auto_20201005_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='spotify',
            field=models.CharField(blank=True, max_length=200, verbose_name='Link para compra'),
        ),
        migrations.AlterField(
            model_name='music',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
