# Generated by Django 3.0.5 on 2020-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0011_auto_20201005_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='spotify',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
