# Generated by Django 3.0.5 on 2020-10-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0013_mysortableclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySortableClass',
        ),
    ]
