# Generated by Django 3.0.5 on 2020-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0014_delete_mysortableclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='exibir',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
