# Generated by Django 3.0.5 on 2020-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0015_alert_exibir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/music')),
                ('exibir', models.BooleanField(blank=True)),
            ],
        ),
    ]
