# Generated by Django 3.0.5 on 2020-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0017_auto_20201005_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
