# Generated by Django 3.0.5 on 2020-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0019_remove_genre_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('saleprice', models.CharField(blank=True, max_length=10)),
                ('exibir', models.BooleanField(blank=True)),
            ],
        ),
    ]
