# Generated by Django 3.0.5 on 2020-10-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0021_pricecard_buylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='soundformat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sound Format'),
        ),
    ]
