# Generated by Django 3.0.5 on 2020-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0022_pricecard_soundformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='audiocopies',
            field=models.CharField(default=1, max_length=10, verbose_name='Audio Copies Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricecard',
            name='audiostream',
            field=models.CharField(default=1, max_length=10, verbose_name='Audio Streams Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricecard',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Preço Final'),
        ),
        migrations.AlterField(
            model_name='pricecard',
            name='saleprice',
            field=models.CharField(blank=True, max_length=10, verbose_name='Preço anterior (ex: antes era esse, agora é Preço Final)'),
        ),
    ]
