# Generated by Django 3.0.5 on 2020-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0023_auto_20201006_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='tagname',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricecard',
            name='soundformat',
            field=models.CharField(max_length=20, verbose_name='Sound Format (audio file)'),
        ),
    ]
